---
- name: create app {{ ssl_cert_root }} subdirectories
  file: dest={{ item }}
        state=directory
        recurse=yes
  with_items:
      - "{{ ssl_cert_root }}/private"
      - "{{ ssl_cert_root }}/certs/"
      
# makeServerKey
- set_fact:
    key_name: "{{ ssl_name }}"

- name: ssl_name.cnf
  template: src=cert_name.cnf.yml
            dest={{ ssl_cert_root }}/certs/{{ key_name }}.cnf

- include: makeServerKey.yml



# server csr
- stat: path={{ ssl_cert_root }}/certs/{{ ssl_name }}.csr
  register: serverCSR

- include: makeServerCSR.yml
  when: serverCSR.stat.exists == False


# makeLocalCA
- stat: path={{ ssl_cert_root }}/certs/localCA.crt
  register: localCA

- include: makeLocalCA.yml
  when: localCA.stat.exists == False

- name: makeSelfSigned
  command: >
    openssl x509 -req  -CAcreateserial -days 3650 \
    -in    "{{ ssl_cert_root }}/certs/{{ ssl_name }}.csr" \
    -out   "{{ ssl_cert_root }}/certs/{{ ssl_name }}.crt" \
    -CA    "{{ ssl_cert_root }}/certs/localCA.crt" \
    -CAkey "{{ ssl_cert_root }}/private/localCA.key"
