---
# makeLocalCA
- stat: path={{ ssl_cert_certs_dir }}/localCA.crt
  register: localCA

- include_tasks: makeLocalCA.yml
  when: localCA.stat.exists == False

- name: makeSelfSigned
  command: >
    openssl x509 -req  -CAcreateserial -days 3650 \
    -in    "{{ ssl_cert_certs_dir }}/{{ ssl_cert_filename }}.csr" \
    -out   "{{ ssl_cert_certs_dir }}/{{ ssl_cert_filename }}.crt" \
    -CA    "{{ ssl_cert_certs_dir }}/localCA.crt" \
    -CAkey "{{ ssl_cert_private_dir }}/localCA.key"
