---
- stat: path={{ ssl_cert_certs_dir }}/{{ ssl_cert_filename }}.csr
  register: ssl_csr

- include_tasks: create_csr.yml
  when: ssl_csr.stat.exists == False

- stat: path={{ ssl_cert_certs_dir }}/{{ ssl_cert_filename }}.crt
  register: ssl_cert

- include_tasks: gen-self-signed.yml
  when: ssl_cert.stat.exists == False

- name: trust local ca
  file: state=link src={{ ssl_cert_certs_dir }}/localCA.crt dest=/usr/local/share/ca-certificates/localCA.crt
  notify: update-ca-certificates
  when: ssl_trust_local_ca

- include_tasks: hdparams.yml
  when: ssl_no_dhparams == False
