---
- name: check if root key exists
  stat: path=/etc/pki/tls/private/{{ key_name }}.key
  register: ssl_key_file

- name: touch root cert or fix permissions
  file: path=/etc/pki/tls/private/{{ key_name }}.key
        state=touch
        owner=root
        mode=600
  when: ssl_key_file.stat.exists == False

- name: makeServerKey
  command: openssl genrsa -out /etc/pki/tls/private/{{ key_name }}.key 4096
  when: ssl_key_file.stat.exists == False
