---
- set_fact:
    key_name: localCA

- include: makeServerKey.yml

- name: localCA.cnf
  template: src=cert_name.cnf.yml
            dest={{ ssl_cert_root }}/certs/{{ key_name }}.cnf

- name: makeLocalCA
  command: openssl req -new -x509 -days 1825 -config "{{ ssl_cert_root }}/certs/localCA.cnf" -key "{{ ssl_cert_root }}/private/localCA.key" -out "{{ ssl_cert_root }}/certs/localCA.crt"
